#*****************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# vivado_proj.tcl: Tcl script for re-creating project 'v_wrp_prj'
#
# Generated by Vivado on Sat Feb 05 06:32:37 UTC 2022
# IP Build 2902112 on Wed May 27 22:43:36 MDT 2020
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (vivado_proj.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/UFAD/andrewsain/LHC_project/2022-01-31/src/*.v"
#    "/home/UFAD/andrewsain/LHC_project/2022-01-31/wrp_dir/wrapper.sv"
#    "/home/UFAD/andrewsain/LHC_project/2022-01-31/constr/timing.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."
set report_dir "$origin_dir/reports"

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "v_wrp_prj"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "vivado_proj.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/v_wrp_prj"]"

# Create project
create_project -force ${_xil_proj_name_} ./${_xil_proj_name_} -part xcvu13p-fsga2577-1-e

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xcvu13p-fsga2577-1-e" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/coord_delay_actual.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/csc_prim_conv11.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/csc_prim_conv_1.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/csc_prim_conv_2.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/duperemoval_layer.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/fullyconnect_actibSr.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/fullyconnect_acticZC.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/fullyconnect_activat.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/fullyconnect_activat_1.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/fullyconnect_activat_2.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/fullyconnect_dense_f.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/fullyconnect_dense_o.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/fullyconnect_dense_o_1.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/fullyconnect_dense_o_2.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/fullyconnect_layer.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/fullyconnect_preproc.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/myproject.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/operator_s.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/pooling_col_argmax_o.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/pooling_fused_col_op.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/pooling_fused_col_op_1.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/pooling_fused_col_op_2.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/pooling_fused_coleOg.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/pooling_fused_colfYi.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/pooling_fused_colg8j.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/pooling_layer.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/pooling_layer_1.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/pooling_layer_2.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/prim_conv_sector.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/rpc_prim_conv.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_am_addmul_14s_cYC.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_mul_sub_6nbTr.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_mul_sub_7scQA.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_10sbDo.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_19sZio.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_19sbIp.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_19scow.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_19scsw.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_19scxx.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_19spcA.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_20s6jw.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_20sb7t.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_20sb9t.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_20sbQq.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_20sbVr.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_20scTB.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_20sckv.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_21s7jG.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_21sbOq.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_21scCy.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_22sb0s.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_22scNA.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5ns9j0.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5nsFfa.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5nsbFp.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5nsbil.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5nsvdy.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_0iy.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_Mgi.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_UhA.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_bGp.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_bPq.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_bek.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_bhl.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_bjl.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_bml.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_cHz.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_cOA.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_cWB.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_czy.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_5s_qcK.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6ns8jQ.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6nsWhU.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6nsbKp.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6nsbLp.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6nsbxn.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6nsbyn.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6nsbzo.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6nscJz.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6nscfu.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6nsocq.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6nstde.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_Aem.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_DeQ.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_Ee0.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_JfO.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_PgM.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_Shg.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_bkl.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_btn.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_bun.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_cGz.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_cPA.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_cgu.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_cmv.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_6s_ctx.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7ns2iS.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7nsQgW.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7nsThq.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7nsb8t.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7nsbAo.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7nsbMq.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7nsbUr.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7nsbbk.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7nscBy.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7nscUB.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7nsclv.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7nssc4.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_1iI.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_Hfu.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_Lf8.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_Yie.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_bBo.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_bWr.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_bpm.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_bsm.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_bvn.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_cDy.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_cIz.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_cLz.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_cbu.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_ncg.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_rcU.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_7s_yd2.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nsCeG.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nsNgs.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nsOgC.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nsRg6.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nsb4t.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nsbCo.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nsbNq.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nsbXr.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nsbak.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nsbnm.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nscwx.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nscyx.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8nsmb6.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_3i2.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_Gfk.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_b5t.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_bYs.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_bll.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_brm.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_bwn.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_cAy.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_cau.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_ccu.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_cdu.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_ceu.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_chv.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_cjv.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_cnw.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_cux.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_8s_wdI.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9nsVhK.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9nsb2s.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9nsbEo.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9nsbZs.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9nscMA.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9nscVB.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9nscrw.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_5jm.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_Xh4.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_b6t.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_bdk.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_bfk.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_bom.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_bqm.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_cFz.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_cSB.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_cXB.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_civ.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_cpw.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mac_muladd_9s_cqw.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_10ns_1bRq.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_10ns_1bck.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_10ns_1cud.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_10ns_1jbC.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_10s_14cEy.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_11ns_1c1C.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_11ns_1dEe.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_11ns_1lbW.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_11s_14c3C.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_12ns_1c0C.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_12s_14c2C.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_13ns_1bkb.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_6ns_13hbi.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_6ns_14zec.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_6s_14s4jc.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_6s_14sbHp.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_7ns_13ibs.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_7ns_14bgk.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_7ns_14xdS.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_7s_14sIfE.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_7s_14scRA.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_8ns_14Bew.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_8ns_14udo.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_8s_14sKfY.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_8s_14sbJp.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_9ns_13kbM.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_9ns_14b3s.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_9ns_14cvx.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mul_mul_9s_14sb1s.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mux_1287_1_1_0.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mux_1287_4_1_0.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mux_1287_6_1_0.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mux_164_1_1_0.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mux_164_3_1_0.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mux_325_28_1_1.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mux_53_32_1_1.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mux_63_13_1_0.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/sp_mux_83_1_1_0.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/trkbuilding_find_ph_s.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/trkbuilding_find_th_s.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/trkbuilding_layer.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/trkbuilding_match_ph.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/trkbuilding_match_ph_1.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/trkbuilding_match_th.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/zonemerging_argmax_o.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/zonemerging_layer.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/zonemerging_preproce.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/zonesorting_argmax_o.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/zonesorting_layer.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/zonesorting_preproce.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/zoning_layer.v"] \
 [file normalize "${origin_dir}/../eHLS_Vivado_project/solution1/impl/verilog/zoning_row_fill_op.v"] \
 [file normalize "${origin_dir}/wrp_dir/wrapper.sv"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/wrp_dir/wrapper.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "wrapper_tf" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constr/timing.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constr/timing.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xcvu13p-fsga2577-1-e" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "wrapper_tf" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcvu13p-fsga2577-1-e -flow {Vivado Synthesis 2020} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2020" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xcvu13p-fsga2577-1-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcvu13p-fsga2577-1-e -flow {Vivado Implementation 2020} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2020" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xcvu13p-fsga2577-1-e" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1


# Synthesize the Design
synth_design
write_checkpoint -force $report_dir/post_synth.dcp
report_timing_summary -file $report_dir/post_synth_timing_summary.rpt
report_utilization -file $report_dir/post_synth_util.rpt

# Logic Optimization
opt_design
reportCriticalPaths $report_dir/post_opt_critpath_report.csv
place_design
report_clock_utilization -file $report_dir/clock_util.rpt

exit