/* LUT generated by lut2cpp by Rafael Hernandez using
 *     'ph_init_neighbor.txt'
 */

#define USE_CONSTEXPR_ph_init_neighbor
#define ph_init_neighbor_MAX_BITS 13
#define ph_init_neighbor_SIZE 732

